version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
  buildAndroid:
    working_directory: ~/repo
      docker:
        - image: circleci/node:10.16.3
      steps:
        - run:
            name: Run android debug build
            command: ./android/gradlew clean

workflows:
  check-source-workflow:
    jobs:
      - test
      - buildAndroid
