version: 2.1
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run lint
          command: yarn lint
  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  build-android:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Android Debug
          command: cd android && ./gradlew assembleDebug

workflows:
  check-source-workflow:
    jobs:
      - lint
      - unit-test
      - build-android
