version: 2.1
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Dependencies
          command: ./yarn.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: yarn lint
  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Dependencies
          command: ./yarn.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
  build-android:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - android-build-{{ checksum "android/gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Install NPM Dependencies
          command: ./yarn.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Android Debug
          command: cd android && ./gradlew assembleDebug
      - save_cache:
          key: android-build-{{ checksum "android/gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ./android/.gradle

workflows:
  check-source-workflow:
    jobs:
      - unit-test
      - lint
      - build-android
