version: 2.1
jobs:
  lint-and-unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run prettier
          command: npx prettier --check "sources/**/*.tsx"
      - run:
          name: Run tests
          command: npm run test
  build-android:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: cd android && ./gradlew assembleDebug

workflows:
  check-source-workflow:
    jobs:
      - lint-and-unit-test
      - build-android
